version: "3.9"
name: RedacteursApp
services:
  frontend:
    build:
      context: ./frontend-web/NewsArticles
      dockerfile: Dockerfile
      args:
        - APIURL=http://localhost:8083/
    ports:
      - 8001:80

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - mysql-db
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"

  mysql-db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: user
      MYSQL_PASSWORD: resu
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql-db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: toor
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
